- data/custom/Code.gitignore
Exclude the Visual Studio Code  '.settings/' directory
> Add Visual Studio Code

- data/custom/LaTeX.gitignore
Newer latexmk installations create these files
> Add *.fls to LaTeX.gitignore

- controllers/api/index.js
Corrected formatting errors as thrown by Travis CI. Should build correctly now.
> Fixed errors thrown by Travis CI

- data/custom/Code.gitignore
https://code.visualstudio.com/Updates#_important-updates-and-breaking-changes
> VS code now uses .vscode instead of .settings

- README.md
- public/README.md
1. clean up duplicate step
2. gi.cmd now is ready to accept multiple parameters.
Signed-off-by: gisphm <phmfk@hotmail.com>
> update gi.cmd in README.md

- controllers/api/index.js
- models/datastore.js
- test/api/index.js
> Support list formats (lines, JSON). Closes #48.

- data/custom/Phoenix.gitignore
Add /rel directory which is generated by [Exrm](https://github.com/bitwalker/exrm).
> Add /rel directory to Phoenix.gitignore

- data/custom/Kobalt.gitignore
@cbeust @joeblau
Issue: https://github.com/joeblau/gitignore.io/issues/184
- Added Kobalt `gitignore`
> Added Kobalt gitignore

- .travis.yml
Fixed travis CI newer node version
> Fixed travis CI

- CONTRIBUTING.md
Fixes path to `.gitignore` files
> Update gitignore directory path

- data/custom/Crossbar.gitignore
Add rules for [crossbar](crossbar.io).
Crossbar creates PID file every time when it starts.
> Added crossbar.io

- data/custom/baserCMS.gitignore
> Modify For all baserCMS Users.

- data/custom/LaTeX.gitignore
> Add *.lol files to LaTeX gitignore

- data/custom/F#.gitignore
> Don't ignore Paket bootstrapper exe

- data/custom/Serverless.gitignore
Serverless Framework: https://serverless.com/
> Add support for Serverless Framework.

- data/custom/Cake.gitignore
Add gitignore for [Cake](http://cakebuild.net/).
> Add gitignore for Cake

- data/custom/Cake.gitignore
Remove comment, since it will be added automatically by webservice
> Remove comment for Cake

- data/patch/Intellij+iml.patch
Remove trailing spaces to be diffable with most editors
> Remove trailing spaces in Intellij+iml.patch

- data/custom/QML.gitignore
> Add support for QML language

- data/custom/CLion.gitignore
> Add CLion Symlink

- data/custom/XamarinStudio.gitignore
> Add Xamarin Studio Packages

- Sources/App/main.swift
- Sources/GitignoreIOServer/Controllers/TemplateController.swift
- Sources/GitignoreIOServer/Extensions/Dictionary+Extensions.swift
- Sources/GitignoreIOServer/Server.swift
- Tests/GitignoreIOServerTests/Controllers/TemplateControllerTests.swift
- Tests/GitignoreIOServerTests/RouteHandlers/APIHandlersTests.swift
- Tests/GitignoreIOServerTests/RouteHandlers/SiteHandlersTests.swift
- Tests/GitignoreIOServerTests/ServerTests.swift
Get to 100% test case coverage
> 100 percent

- data/custom/Laravel.gitignore
Ignorable files according to the latest version of Laravel.
Just copied the missing lines from the Laravel out of the box .gitignore file.
> Missing Laravel files to be ignored

- data/custom/SwiftPackageManager.gitignore
Just noticed this typo from my previous PR.....sorry! 🙈
> Fix typo for relative derived data for SPM projects

- data/custom/Angular.gitignore
Hi, awesome project.
I was looking an Angular project gitignore file and there is not support for that in your page.
I decided to create this pull request for support Angular projects.
> Add support for Angular projects

- data/patch/Intellij.patch
> Add Sonar Lint to Intellij.Patch

- data/custom/Xcode.gitignore
This folder contains data that are intended to be shared.
Steps to create it:
Product > Scheme > Manage Schemes...
Mark the "Shared" checkbox
> Remove xcshareddata folder from gitignore

- README.md
It failed with F# or C++ for example.
> Escape special characters

- data/custom/pydev.gitignore
http://www.pydev.org
This is an eclipse based IDE for Python.
So eclipse and python ignores are also a good call to anyone consuming things
> Ignoring pydev files

- data/custom/CodeComposerStudio.gitignore
Fixes #337 - Add support for Code Composer Studio
> Fixes #337 - Add support for Code Composer Studio

- Localization/pt-BR.json
> Update pt_BR translation

- .dockerignore
- Dockerfile
- README.md
- docker-compose.yml
This pull request adds the necessary files to run the app using Docker and Docker Compose. It should works in any environment that runs Docker, but I just tested on Linux. Also the `README.md` file was updated with usage instructions in case someone using a Mac or Windows machine would like to test it.
> Add Docker support

- Procfile
- Resources/Views/docs.leaf
- Resources/Views/index.leaf
- Sources/App/RouteHandlers/SiteRouteHandlers.swift
> Disable prod check

- Localizations/fa_IR.json
I add persian translation fore localization
> Adding Translation file

- Localizations/ko_KR.json
This pull request adds Korean localization file `/Localizations/ko_KR.json` into the project.
This pr closes #444
> Add Korean translation

- Localizations/ro_RO.json
Hi,
Here is the Romanian translation for the project. Hope it helps.
Regards,
Vlad
> Romanian translation

- Localizations/zh_CN.json
the tranlation for Simplified Chinese
> chinese translation

- README.md
Clone of https://github.com/toptal/gitignore.io/pull/478
> fixed build status badge on README

- Localizations/id-ID.json
I added an `id-ID.json` file for Indonesian translation. Any suggestions will be appreciated, thanks.
> feat: add Indonesian translation

- Localizations/ja_JP.json
I added a `ja_JP.json` file for Japanese translation. Any suggestions will be appreciated, thank you.
> feat: add Japanese translation

- Public/css/app.css
- Public/css/app.less
- Public/css/internal-linking.less
- Public/css/variables.less
- Resources/Views/index.leaf
- Resources/Views/internal-linking.leaf
- Resources/links.json
- Sources/App/Controllers/InternalLinkingController.swift
- Sources/App/Models/InternalLink.swift
- Sources/App/RouteHandlers/SiteRouteHandlers.swift
- Sources/App/Server.swift
[TRA-1517](https://toptal-core.atlassian.net/browse/TRA-1517)
Replacing the current implementation with the canonical one  (local data .json file + template extraction at the project level)
- docker-compose -f ./docker-compose-dev.yml build
- docker-compose -f ./docker-compose-dev.yml up
- go to [http://localhost:8080](http://localhost:8080)
- verify if internal linking bar is in place, and not loaded through iframe
- click/middle click on the links from the widget. Events should register in the Tag Assistant Extension
- everything else should work as expected (no regression)
> [TRA-1517] Update internal linking

- Localizations/cs.json
- Sources/App/Extensions/Router+Extensions.swift
> Add czech language
