toptal/gitignore.io

- data/custom/jspm.gitignore
I'd like to propose adding a gitignore for the [jspm](http://www.jspm.io) package manager.
> add gitignore for jspm

- data/custom/Carthage.gitignore
Lately i am using Carthage for dependency management and noted that your project was was missing a carthage gitignore file, so i created this pull request.
> Add gitignore for Carthage

- data/custom/Laravel.gitignore
Update file to include ignore files relevant to both Laravel 4 and Laravel 5 projects. Based on current .gitignore file ( see https://github.com/laravel/laravel/blob/master/.gitignore )
> Update Laravel.gitignore for Laravel 5

- data/custom/LiberoSOC.gitignore
I've updated the Libro SOC ignore file to exclude more built files. Some of these files can get rather large and clog projects and they are not absolutely necessary to keep in tracking.
> updated Libero SOC ignore

- data/custom/phoenix.gitignore
Phoenix is a web framework for Elixir.
This .gitignore file ignores all the dependencies and compiled files by elixir, as
well as node_modules and compiled static sources in the priv directory (such
as compiled sass files).
> Added Phoenix .gitignore file

- public/templates/index.dust
This commit is meant to resolve issue #132 
Removed the set placeholder value from the input field. Placeholder now being set only by select2 (I think). Works correctly when run locally in Chrome and Firefox.
> Bug Fix. Duplicated placeholder on initial search input

- data/custom/Django.gitignore
A default install of Django sets the SQLite DB filename to be `db.sqlite3` which should be ignored and git and not replicated to other environments.
Also, `media` is a very common directory name where user-uploaded files are saved. This should also be ignored.
> Update gitignore entries for Django

- data/custom/Terraform.gitignore
Terraform defaults to storing its state files locally but given the information they contain, they should not be committed.
I consider ignoring these files to be a _sane default_.
> updates ignored files for Terraform

- controllers/api/index.js
Adds a leading newline, since sometimes existing `.gitignore` files don't have a trailing newline, causing e.g. `gi node >> .gitignore` to merge with the last existing line.
> Leading newline.

- data/custom/fastlane.gitignore
[fastlane](https://fastlane.tools) is a tool to connect all iOS deployment workflow. These folder/files should be ignored as [suggested](https://github.com/fastlane/fastlane/blob/master/docs/Gitignore.md).
> Add support for fastlane

- public/templates/index.dust
Having a `tabindex=-1` on both the Generate and dropdown buttons
means that they are unacessible via keyboard. That is very hurtful
for acessibility and downright annoying when using the website
instead of the cli helper function.
> Remove tabindex -1 from Generate button

- data/custom/Kirby2.gitignore
Kirby prevents brute-force attacks with a `.logins` file in `site/accounts`, [see here](https://forum.getkirby.com/t/what-is-site-accounts-logins/3494). If this file doesn't exist, Kirby generates a new one. Tracking this file in git doesn't make much sense. It also could cause a conflict, if someone deploys Kirby with git.
> Ignore all account files in Kirby2

- data/custom/LiberoSOC.gitignore
This is a more exclusive handling of the files in the smartgen folder. This will only keep the .vhd and .gen files that are needed.
> Tweak to handling of LiberoSOC smartgen files

- data/custom/Terraform.gitignore
Terraform can optionally load environment specific variables from a *.tfvars file,
by default a `terraform.tfvars` file.  These files may contain secrets.
See https://www.terraform.io/intro/getting-started/variables.html
> Ignore Terraform tfvars files

- data/custom/Ember.gitignore
[Ember.js](http://emberjs.com/) is "a framework for creating ambitious web applications". A command line interface exists to set an Ember project : [Ember CLI](http://ember-cli.com/). I took the gitignore file contents [here](https://github.com/ember-cli/ember-cli/blob/master/blueprints/app/files/gitignore).
> Add Ember.gitignore

- controllers/api/index.js
This removes 2, IMO, misplaced `\n`s:
1. The one in the "file header" seems to be placed there intentionally, though I'm not sure why. It causes the first line in my .gitignore files to be blank which I'm not a huge fan of.
2. I added a conditional to the `\n` that separates the different gitignore templates in 1 file so that the last one doesn't have a `\n` added. Apparently git doesn't want .gitignore files to end with `\n`.
> Remove misplaced \n

- data/custom/JabRef.gitignore
Not sure, whether URLs should be included at all. But if, then they should point to the most recent one even though [Cool URIs don't change](https://www.w3.org/Provider/Style/URI).
> Fix URL of JabRef

- data/custom/Code.gitignore
Add tsconfig.json and jsconfig.json to data/custom/Code.gitignore
I know some projects want these files to be committed to git, but I think that because they are editor-specific files that are automatically generated for every project they should be excluded by default.
> Add tsconfig.json/jsconfig.json to Code.gitignore

- data/patch/Tex.patch
The contained patch for pdfcomment is already available at https://github.com/github/gitignore/blob/master/TeX.gitignore. Thus, this patch file is obsolete.
> Remove Tex.patch as the contained patch is already available at github

- data/custom/Blackbox.gitignore
blackbox automatically adds these ignore lines to .gitignore if they are not
present already, so it should be safe to make gitignore.io to add it, there
will be no duplication.
See:
https://github.com/StackExchange/blackbox/blob/master/bin/blackbox_initialize#L30
https://github.com/StackExchange/blackbox/blob/master/bin/_blackbox_common.sh#L586-L595
> Add StackExchange's blackbox secret management

- data/custom/Synology.gitignore
Synology NAS devices create some junk directories which is not easy or even
possible to remove.
https://www.synology.com/en-global/knowledgebase/DSM/help/DSM/AdminCenter/file_share_recycle
http://www.coderzen.com/2015/03/12/how-to-stop-your-synology-nas-from-junking-up-your-directories-with-eadir-directories/
> Added Synology

- data/custom/Carthage.gitignore
These must have changed somewhere in Carthage's history.
Carthage now nests Build and Checkouts directories under
a Carthage directory, rather than creating two directories
directly alongside the Cartfile.
> Update ignored Carthage directory paths

- data/custom/Crashlytics.gitignore
The files `crashlytics.properties` and `fabric.properties` contains API Secret used to validate application with crashlytics / fabric API. You should not commit these files to public repository.
> Added missing fabric/crashlytics files to .gitignore

- data/custom/Archive.gitignore
- data/custom/CompressedArchive.gitignore
- data/custom/Compression.gitignore
- data/custom/DataRecovery.gitignore
Added Archive.gitignore Compression.gitignore, CompressedArchive.gitignore and DataRecovery.gitignore to data/custom.
There were so many filetypes I decided to categorize.  I decided to put package managers into Archive as I did not want to create a 5th file.
There is already a gitignore/Global/Achives.gitignore, but mine has comments of each filetype and is more thorough.
Tested and working locally.
> Added Archive, Compression, CompressedArchive and DataRecovery

- README.md
Add a subsection to 'Other Clients' section where people can list tools and extensions that are built on top of/use the gitignore.io API.
> Add table for tools and extensions in README.md

- controllers/api/index.js
- test/api/index.js
This is a stop-gap which will partially solve issue #83 (won't completely fix it as this will only work for regexes that are *exactly* the same).
These proposed changes:
- Add a new function which is run on the output gitignore file string, and removes all duplicate lines except blank strings and comments
- Add a unit test for the gitignore endpoint (when just one language is selected)
- Add a unit test for the gitignore endpoint (when two very similar languages selected) - this test is currently failing as I'm not sure quite how to write it in a way that will not require assuming the content of gitignore files or using the same function I wrote to remove duplicates.
> Remove duplicate lines from gitignore file output

- public/js/app.js
I've picked up the habit of pressing Cmd+Enter to submit reddit comments and posts because of Reddit Enhancement Suite. Over time, I noticed that it's a somewhat standard keyboard shortcut across the web; even GitHub supports it. I miss it on gitignore.io, so I decided to build it in. This modification still supports the old Enter-to-select, but adds a new Cmd/Ctrl+Enter shortcut to submit the search query.
It was pretty tricky to implement.
I also increased the timeout time to focus the input box to 100ms, because 10ms was a hit or miss. Select2 seems to take approximately that long to set up its search box.
> Added Cmd/Ctrl+Enter functionality to search box

- data/custom/JMeter.gitignore
JMeter is a tool for performing Load/Performance testing. Usually, their TestCases which are JMX files can be committed as a Git Repository.
This simple gitignore makes it better for ignoring common ignore files for the same.
> Added JMeter gitignore

- data/custom/Shopware.gitignore
Both `/internal/` as well as `/engine/Shopware/Plugins/Commercial/` don't exist in a default Shopware-installation at all.
> Remove non-existing plugin-dirs

- README.md
It creates an [autoloading function](https://fishshell.com/docs/current/tutorial.html#tut_autoload) in [fish shell](https://fishshell.com). Sourcing it is not required as fish shell autoloads functions.
Notes:
* Using `printf` for [better](http://unix.stackexchange.com/questions/65803/why-is-printf-better-than-echo) new-line (`\n`) support instead of `echo`. New-lines make the function more human-readable.
* Using `>` as `gi.fish` should only contain this one function. Hence, appending to the file is not required.
Testing:
* ✅ Manually tested on macOS Sierra v10.12.3 (16D32) with iTerm2 v3.0.13 with fish shell v2.5.0.
* ❌ Was not able to test on Linux.
Suggestions for improvement are welcome! Thanks!
> Add CLI installation instructions in fish on Linux & macOS.

- data/custom/SwiftPackageManager.gitignore
- data/custom/Xcode.gitignore
This PR adds the `DerivedData` directory to the gitignore for those who have Relative Derived Data configured in Xcode
> Add relative derived data for Xcode projects

- data/custom/Crystal.gitignore
Crystal introduce `shards` as it's default dependency management system, so .gitignore was updated.
> Update Crystal .gitignore

- data/custom/Kentico.gitignore
Adds an include rule for default continuous integration folder, a new rule for an updated path in version 10, a few headers, and fixes a typo.
> Update Kentico ignore

- Sources/GitignoreIOServer/RouteHandlers/APIRouteHandlers.swift
It's a small thing, but I find the lack of a newline before the closing comment makes the final line of the template code harder to read. This just makes the closing comment more consistent with the opening one.
> Add newline between last template line and closing comment.

- Sources/App/Controllers/TemplateController.swift
- Sources/App/RouteHandlers/APIRouteHandlers.swift
- Sources/App/Server.swift
- Tests/AppTests/RouteHandlers/APIHandlersTests.swift
Add `/api/order` endpoint for services which want to sort templates the same way gitignore.io does.
> Add order API endpoint

- Public/js/app.js
Added URL Params so keywords can be populated on first load. On loading `templates.json`, it’ll now extract URLParams and filter out those params that exist in the templates. It’ll then “fill” them in the `select2` Search box.
Signed-off-by: Robin Malhotra <me@rmalhotra.com>
> Add url params to gitignore.io

- README.md
I've created a small utility that extends the `git` command so that you can list templates from gitignore.io with `git ignore --list` instead of having to remember a separate command. I was unsure on whether I should also edit the README in the `Public/` folder, so let me know if I should change anything. Thanks for the service! Use it all the time :smile:
> Add git-ignore Rust tool for listing and getting templates

- Public/js/app.js
This commit will fix #435 by adding `encodeURIComponent()` function to split values from `template` url parameter. The `+` letter in them will be url encoded. Some special characters are encoded as well: `, / ? : @ & = $ #`
I hope this commit will suffice to solve this problem.
cc. @codeOfRobin
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent
* #429
> Fix #435 by adding encodeURIComponent()

- Public/js/app.js
Pull request #437 actually didn't solve the closed issue #435 because I understood the problem wrong. This problem was not about url encoding.
`URLSearchParams` object returns invalid id of `gitignore.io` template not because the object didn't recognize `+` letters, but because it ACTUALLY recognized them and switched them to SPACES(` `).
To solve the problem correctly, this pull request changes strategy to replace spaces to `+` in url parameter, so the filter is able to find proper id from template set.
This pull request also includes small refactoring in `app.js`.
cc. @codeOfRobin 
* https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams
> Fix #437 - the "+" letter problem

- Dockerfile
Bumps swift to the latest available version in v4 branch.
To test manually:
```
docker-compose up --build
```
visit http://localhost:8080
> Bump swift from v4.1 to v4.2.4

- Sources/App/RouteHandlers/APIRouteHandlers.swift
Fixing the issue outlined in https://github.com/toptal/gitignore.io/issues/504
- Run `docker-compose -f ./docker-compose-dev.yml up --build`
- Visit http://0.0.0.0:8080/api/macos
- To check if `\r\r` is present you can do use `irb`
```
require 'net/http'
require 'uri'
Net::HTTP.get_response(URI.parse("http://0.0.0.0:8080/api/macos")).body
```
You should see two `\r` after Icon:
```
=> "\n# Created by https://www.toptal.com/api/macos\n# Edit at https://www.toptal.com?templates=macos\n\n### macOS ###\n# General\n.DS_Store\n.AppleDouble\n.LSOverride\n\n# Icon must end with two \\r\nIcon\r\r\n\n# Thumbnails\n._*\n\n# Files that might appear in the root of a volume\n.DocumentRevisions-V100\n.fseventsd\n.Spotlight-V100\n.TemporaryItems\n.Trashes\n.VolumeIcon.icns\n.com.apple.timemachine.donotpre …
```
> Fix Icon\r\r

- Public/js/app.js
- Resources/Views/index.leaf
-  Change Google Analytics Implementation
- Check if Google Analytics is still loaded on gitignore.
- Check if `content_group` is `Git Ignore`.
> [TRA-1102] Change Gitignore.io content group implementation

- Localizations/ja.json
Hi! Thanks for developing an awesome application!!
I've noticed a typo and some expressions that seemed to be translated too literally in the `ja_JP.json`
I've changed the corresponding Japanese for 
- "commandLineTitle" (typo)
- "videoDescription" (minor change)
- "sourceCodeDescription" (minor change)
For the "videoDescription", I thought the original expression 
was too literally translated.
> .gitignore.ioがどのように機能するかを学ぶためにビデオを見る
(Meaning like, "Watch the video to learn how the _function_ of .gitignore.io works")
I've changed to a more natural expression.
And for the "sourceCodeDescription", I thought the word
> GitHubホストソースコード
was bit unnatural.
But I wasn't really sure if my understanding of the original EN sentence is correct.
Does
> "GitHub hosted source code for .gitignore.io" …
> fix: Japanese translation

- Resources/Views/internal-linking.leaf
Gitignore runs on a subpath of toptal.com
thus image paths need to be relative
Bug introduced by https://github.com/toptal/gitignore.io/pull/534
> [TRA-1694] Fix image path

- Public/css/app.css
- Public/css/app.less
- Resources/Views/index.leaf
[TRA-1694](https://toptal-core.atlassian.net/browse/TRA-1694)
After deploying for testing, it was discovered that loading these fonts
under the head tag may cause a browser error, which would drop ou
webvitals score.
Related to https://github.com/toptal/gitignore.io/pull/534
- docker-compose -f ./docker-compose-dev.yml build
- docker-compose -f ./docker-compose-dev.yml up
- go to [http://localhost:8080](http://localhost:8080)
- verify that the app is still overall working
- verify e2e tests are passing with `yarn test`
- use browser performance tools with webvitals enabled to check for issues
> [TRA-1694] Declare fonts on app.css instead of head and preload

- docker-compose-dev.yml
[SAT-284](https://toptal-core.atlassian.net/browse/SAT-284)
Defining the platform on docker-compose-dev will help OSx users
prevent build issues, particularly Apple Silicon users.
* Run `docker-compose -f ./docker-compose-dev.yml up --build`
* It should work on your platform
> [SAT-284] Define platform on docker-compose-dev
